#include <iostream>
#include <chrono> 
#include "FunctionalTests.hpp"
#include "PerformanceTests.hpp"

/*
* Description of the test files in ~/ResourceFiles directory:
* letter_in_number 9465a.00000000
* no_valid_number a94654.00000000
* number_out_of_range 123456789.123456789123
* missing_s {"e": "depthUpdate", "E": 1745652665014, "b": [["94650.00000000", "5.72464000"]], "a": [["94650.01000000", "1.00672000"]]}
* missing_a {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT", "b": [["94650.00000000", "5.72464000"]]}
* missing_b {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT", "a": [["94650.00000000", "5.72464000"]]}
* binance_stream_output - data from binance stream
* multiple_curencies {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT", "b": ... 
                     {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT1", "b": ...
* repeated_data {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT", "b": [["94650.00000000", "5.72464000"],... 
                {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT", "b": [["94650.00000000", "5.72464000"],...
* update_existing_entry {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT", "b": [["94650.00000000", "5.72464000"], ...
*                       {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT", "b": [["94650.00000000", "1.00000000"], ...
* zero_value_for_bid_initially {"e": "depthUpdate", "E": 1745652665014, "s": "BTCUSDT", "b": [["94654.00000000", "00000000.00000000"]],...
*/

int main() {

    FunctionalTests ftOrder;
    ftOrder.runALlTests();

    std::string dataBaseFile = "ResourceFiles/multiple_curencies.txt";
    PerformanceTests performanceTests;
    performanceTests.testWithAutogeneratedData(10, 10, 10, 0);
    performanceTests.testWithDataBaseFile(dataBaseFile, 0);
    return 0;
}