#pragma once
#include <chrono>
#include "Tools.hpp"
#include "OrderBook.hpp"

class PerformanceTests {

public:

	PerformanceTests() = default;
    /* Performs time and memory consumption test on map and unordered_map order book.
    * Autogenerated source of data is used
    * int entriesCount 
    * int bidCount
    * int asksCount
    * int printDetails 0 - few details; 1 - more details
    */
    int testWithAutogeneratedData(int entriesCount, int bidCount, int asksCount, int printDetails) {
        std::map<std::string, std::map<ull, ull, OrderBook::DescendingComparator>> orderBookBids; // biggest bid at the top - faster search for best price
        std::map<std::string, std::map<ull, ull>> orderBookAsks; // smallest asks at the top - faster search for best price
        std::unordered_map<std::string, std::unordered_map<ull, ull>> unorderBookBids;
        std::unordered_map < std::string, std::unordered_map<ull, ull>> unorderBookAsks;
        OrderBook orderBook(orderBookBids, orderBookAsks);
        OrderBook unOrderBook(unorderBookBids, unorderBookAsks);
        consoleWriteInColors("!!!Ordered map book test with autogenerated data!!!", YELLOW);
        int resultOrder = timeMeasurements(orderBook, entriesCount, bidCount, asksCount, orderBookBids, orderBookAsks);
        if (resultOrder) {
            std::cout << __func__ << ": Error has occured!" << std::endl;
            return 1;
        }
        memoryConsumption(orderBookBids);
        memoryConsumption(orderBookAsks);
        orderBook.printOrderBook(orderBookBids, orderBookAsks, printDetails);
        orderBook.printBestOffers(orderBookBids, orderBookAsks);
        std::cout << std::endl;
        consoleWriteInColors("!!! Unordered map book test with autogenerated data!!!", YELLOW);
        int resultUnOrder = timeMeasurements(unOrderBook, entriesCount, bidCount, asksCount, unorderBookBids, unorderBookAsks);// int entriesCount, int bidCount, int asksCount
        if (resultUnOrder) {
            std::cout << __func__ << ": Error has occured!" << std::endl;
            return 1;
        }
        memoryConsumption(unorderBookBids, "bids");
        memoryConsumption(unorderBookAsks, "asks");
        unOrderBook.printOrderBook(unorderBookBids, unorderBookAsks, printDetails);
        unOrderBook.printBestOffers(unorderBookBids, unorderBookAsks);
        std::cout << std::endl;
    }

    /* Performs time and memory consumption test on map and unordered_map order book.
    * Data base file is source of data
    * string& dbFile Data base file to be used as data source
    * int printDetails 0 - few details; 1 - more details
    */
    int testWithDataBaseFile(std::string& dbFile, int printDetails)
    {
        std::map<std::string, std::map<ull, ull, OrderBook::DescendingComparator>> orderBookBids; // biggest bid at the top - faster search for best price
        std::map<std::string, std::map<ull, ull>> orderBookAsks; // smallest asks at the top - faster search for best price
        std::unordered_map<std::string, std::unordered_map<ull, ull>> unorderBookBids;
        std::unordered_map < std::string, std::unordered_map<ull, ull>> unorderBookAsks;
        OrderBook orderBook(orderBookBids, orderBookAsks);
        OrderBook unOrderBook(unorderBookBids, unorderBookAsks);
        consoleWriteInColors("!!! Ordered map book test with data base file!!!", YELLOW);
        int resultOrder = timeMeasurements(orderBook, dbFile, orderBookBids, orderBookAsks);
        if (resultOrder) {
            std::cout << __func__ << ": Error has occured!" << std::endl;
            return 1;
        }
        memoryConsumption(orderBookBids);
        memoryConsumption(orderBookAsks);
        orderBook.printOrderBook(orderBookBids, orderBookAsks, printDetails);
        orderBook.printBestOffers(orderBookBids, orderBookAsks);
        std::cout << std::endl;
        consoleWriteInColors("!!! Unordered map book test with data base file!!!", YELLOW);
        int resultUnOrder = timeMeasurements(unOrderBook, dbFile, unorderBookBids, unorderBookAsks);
        if (resultUnOrder) {
            std::cout << __func__ << ": Error has occured!" << std::endl;
            return 1;
        }
        memoryConsumption(unorderBookBids, "bids");
        memoryConsumption(unorderBookAsks, "asks");
        unOrderBook.printOrderBook(unorderBookBids, unorderBookAsks, printDetails);
        unOrderBook.printBestOffers(unorderBookBids, unorderBookAsks);
        std::cout << std::endl;
    }
private:

    int timeMeasurements(OrderBook& orderBook, std::string& dbFile, std::map<std::string, std::map<ull, ull, OrderBook::DescendingComparator>>& bookBids, std::map<std::string, std::map<ull, ull>>& bookAsks) {
        auto startTime = std::chrono::high_resolution_clock::now();
        int result = orderBook.bookUpdate(bookBids, bookAsks, dbFile);
        auto endTime = std::chrono::high_resolution_clock::now();

        if (result != 0) {
            std::cerr << __func__ << ": Error has occured!" << std::endl;
            return 1;
        }

        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(endTime - startTime);
        std::cout << "Time taken to fill the order book: " << duration.count() << " microseconds" << std::endl;
        return 0;
    }
    int timeMeasurements(OrderBook& orderBook, int entriesCount, int bidCount, int asksCount, std::map<std::string, std::map<ull, ull, OrderBook::DescendingComparator>>& bookBids, std::map<std::string, std::map<ull, ull>>& bookAsks) {
        auto startTime = std::chrono::high_resolution_clock::now();
        int result = orderBook.bookUpdate(bookBids, bookAsks, entriesCount, bidCount, asksCount);
        auto endTime = std::chrono::high_resolution_clock::now();

        if (result != 0) {
            std::cout << "Error has occured!" << std::endl;
            return 1;
        }

        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(endTime - startTime);
        std::cout << "Time taken to fill the order book: " << duration.count() << " microseconds" << std::endl;
        return 0;
    }
    int timeMeasurements(OrderBook& orderBook, std::string& dbFile, std::unordered_map<std::string, std::unordered_map<ull, ull>>& unbookBids, std::unordered_map < std::string, std::unordered_map<ull, ull>>& unbookAsks) {
        auto startTime = std::chrono::high_resolution_clock::now();
        int result = orderBook.bookUpdate(unbookBids, unbookAsks, dbFile);
        auto endTime = std::chrono::high_resolution_clock::now();

        if (result != 0) {
            std::cerr << __func__ << ": Error has occured!" << std::endl;
            return 1;
        }

        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(endTime - startTime);
        std::cout << "Time taken to fill the unorder book: " << duration.count() << " microseconds" << std::endl;
        return 0;
    }
    int timeMeasurements(OrderBook& orderBook, int entriesCount, int bidCount, int asksCount, std::unordered_map<std::string, std::unordered_map<ull, ull>>& unbookBids, std::unordered_map < std::string, std::unordered_map<ull, ull>>& unbookAsks) {
        auto startTime = std::chrono::high_resolution_clock::now();
        int result = orderBook.bookUpdate(unbookBids, unbookAsks, entriesCount, bidCount, asksCount);
        auto endTime = std::chrono::high_resolution_clock::now();

        if (result != 0) {
            std::cout << "Error has occured!" << std::endl;
            return 1;
        }

        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(endTime - startTime);
        std::cout << "Time taken to fill the unorder book: " << duration.count() << " microseconds" << std::endl;
        return 0;
    }
    void memoryConsumption(std::map<std::string, std::map<ull, ull>>& myMap) {
        // main map
        size_t mainMapKeySize = sizeof(std::string);
        size_t mainMapNodeOverhead = 3 * sizeof(void*); // Tree pointers: parent, left, right
        size_t mainMapMem = myMap.size() * (mainMapKeySize + mainMapNodeOverhead);
        // inner map
        size_t innerMapKeySize = sizeof(unsigned long long);
        size_t innerMapValueSize = sizeof(unsigned long long);
        size_t innerMapNodeOverhead = 3 * sizeof(void*); // Tree pointers: parent, left, right
        size_t constMemConsumption = innerMapKeySize + innerMapValueSize + innerMapNodeOverhead;

        // inner map memory consumption calculation
        size_t innerMapMem = 0;
        for (const auto& [symbol, asks] : myMap) {
            //std::cout << "Symbol: " << symbol << std::endl;
            //std::cout << "Inner map size = " << bids.size() << std::endl;
            innerMapMem += asks.size() * constMemConsumption;
        }
        size_t totalMem = mainMapMem + innerMapMem;
        std::cout << "Total mem consumption asks: " << totalMem << " Bytes" << std::endl;
    }
    void memoryConsumption(std::map<std::string, std::map<ull, ull, OrderBook::DescendingComparator>>& myMap) {
        // main map
        size_t mainMapKeySize = sizeof(std::string);
        size_t mainMapNodeOverhead = 3 * sizeof(void*); // Tree pointers: parent, left, right
        size_t mainMapMem = myMap.size() * (mainMapKeySize + mainMapNodeOverhead);
        // inner map
        size_t innerMapKeySize = sizeof(unsigned long long);
        size_t innerMapValueSize = sizeof(unsigned long long);
        size_t innerMapNodeOverhead = 3 * sizeof(void*); // Tree pointers: parent, left, right
        size_t constMemConsumption = innerMapKeySize + innerMapValueSize + innerMapNodeOverhead;

        // inner map memory consumption calculation
        size_t innerMapMem = 0;
        for (const auto& [symbol, bids] : myMap) {
            //std::cout << "Symbol: " << symbol << std::endl;
            //std::cout << "Inner map size = " << bids.size() << std::endl;
            innerMapMem += bids.size() * constMemConsumption;
        }
        size_t totalMem = mainMapMem + innerMapMem;
        std::cout << "Total mem consumption bids: " << totalMem << " Bytes" << std::endl;
    }
    void memoryConsumption(std::unordered_map<std::string, std::unordered_map<ull, ull>> myMap, std::string bidOrAsk) {
        std::size_t totalBytes = sizeof(myMap);

        for (const auto& [source, bids] : myMap) {
            totalBytes += source.capacity(); // Account for string storage
            totalBytes += sizeof(bids);
            totalBytes += bids.size() * (sizeof(ull) * 2); // Each bid pair (price ->quantity)
        }

        std::cout << "Total mem consumption " << bidOrAsk << ": " << totalBytes << " Bytes" << std::endl;
    }
};